[package]
name = "rust"
version = "0.1.0"
authors = ["moon548834 <fzp548834@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.3.8"
